### ISSUE TITLE
Problems using ecto in parallell with arangox_ecto

### ISSUE THREAD

**Issue by maxmannen** [TomGrozev/arangox_ecto#10]
Encountered a problem when using arangox_ecto togethether with ecto.
It seem that this is due to modules are sharing the same name; migrate and migration.
One solution is to rename these.
See the issue here: [https://elixirforum.com/t/problems-with-deployment-on-gigalixir-using-two-databases/35717](url) and solution here: [https://github.com/bitwalker/distillery/issues/372](url)

**Comment by TomGrozev** [comment]
The module is built so that you do not need to include `ecto_sql`. Some frameworks such as Phoenix will automatically include `ecto_sql`, you need to remove this from your mix.exs file.

**Comment by maxmannen** [comment]
Thanks for this. Very helpful.
Yes, my plan is to use both as I want to keep user data and such in Postgres but I will consider another approach.

**Comment by TomGrozev** [comment]
Ah, ok. I will implement this and get back to you.

**Comment by churcho** [comment]
> Thanks for this. Very helpful.
> Yes, my plan is to use both as I want to keep user data and such in Postgres but I will consider another approach.

Please share what you land on as this is in my radar as well. I'd like to use Postgres for some Account management and defer most of the core logic that needs graph data to ArangoDB.

**Comment by TomGrozev** [comment]
Checkout this branch and let me know if it fixes your issue @maxmannen 

https://github.com/TomGrozev/arangox_ecto/tree/fix/mix-task-conflicts

**Comment by maxmannen** [comment]
This is great!
No errors when uploading to Gigalixir...
I will get back if I encounter other errors.

**Comment by maxmannen** [comment]
Works like a charm both locally and in production(Gigalixir)
