### ISSUE TITLE
Ecto 3.5 support

### ISSUE THREAD

**Issue by ebostijancic** [TomGrozev/arangox_ecto#12]
Any plans when Ecto 3.5 is supported?

**Comment by TomGrozev** [comment]
Reading the changelog of Ecto 3.5.x there seems to be no issues that would break it. I will have to run some tests to double check.

If you would like to try it yourself in the meantime, checkout the update/ecto-3.5 branch.

**Comment by TomGrozev** [comment]
No issues were found with he changes to Ecto. This has been pushed in v0.6.9 which is now live.
