### ISSUE TITLE
Error on `mix ecto.setup.arango`

### ISSUE THREAD

**Issue by krezicoder** [TomGrozev/arangox_ecto#26]
I am facing an error on running `mix ecto.setup.arango`

Phoenix Version : Phoenix v1.6.2
{:arangox_ecto, "~> 0.7.2"}

```
❯ mix ecto.setup.arango

==> velocy
Compiling 6 files (.ex)
Generated velocy app
==> arangox
Compiling 10 files (.ex)
Generated arangox app
==> arangox_ecto
Compiling 16 files (.ex)
Generated arangox_ecto app
==> arango_db_api
Compiling 11 files (.ex)
Generated arango_db_api app
** (CaseClauseError) no case clause matching: {:ok, %Arangox.Response{body: %{"code" => 201, "error" => false, "result" => true}, headers: %{}, status: 201}}
    (arangox_ecto 0.7.2) lib/mix/arangox_ecto.ex:22: Mix.ArangoXEcto.create_database/0
    (arangox_ecto 0.7.2) lib/mix/tasks/ecto.setup.arango.ex:15: Mix.Tasks.Ecto.Setup.Arango.run/1
    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2
    (elixir 1.12.3) lib/code.ex:1261: Code.require_file/2
```

Db is created though in the Arango Web Interface

**Comment by TomGrozev** [comment]
> @TomGrozev Thanks for the response. I will look forward to the new release. Can you pls let me know a timeline for the new release ?

Sorry @krezicoder, didn't see you question until now. I have been very busy but I plan to release version 1.0.0 before Christmas this year. There remains only two more features that are to be added, they are multi-tenancy and dynamic and static collection management. These must be completed in this version as they are major breaking changes.

**Comment by Storycrafter** [comment]
@TomGrozev is there any way to another dev to help?

**Comment by TomGrozev** [comment]
> @TomGrozev is there any way to another dev to help?

Testing of the release would be a massive help. I have been working on multi-tenancy and am starting to think I might push this feature as it will require some working. I would like to have the release published this week.

Over the next couple days I will be cleaning up some code.

**Comment by Storycrafter** [comment]
Sounds like a plan. I will see what I can do to help.

**Comment by TomGrozev** [comment]
Version 1.0.0 has now been published so I will close this. If it hasn't been resolved please reopen.

For reference, the commit fixing this issue is: 9bf68c3d519dfdaa6033b94acb7d40d130c4e92b
