### ISSUE TITLE
keyOptions for collection keys

### ISSUE THREAD

**Issue by rxndxm** [TomGrozev/arangox_ecto#33]
### ArangoXEcto version

v1.0.0

### Feature type

Change to existing functionality

### Proposed functionality

I'm not seeing a way to set options when creating a collection as described here:

https://www.arangodb.com/docs/stable/http/collection-creating.html

Please let me know if I'm missing something - big fan of this project 🙏

### Use case

Ability to set UUID or Padded as key types, and other collection options

**Comment by TomGrozev** [comment]
This is a really good suggestion. For migrations this would be pretty simple to implement but for dynamic this would be a bit more complex as it would require some settings in the schema. I reckon this is a good idea for v1.1.

I will probably start playing around with this soon (dependant on work load) or if you wanted to give it a crack that would be great too.

**Comment by rxndxm** [comment]
I'm new to the library still, but will keep learning and see what I can do!

**Comment by TomGrozev** [comment]
As a note for documentation purposes:
When working on this I realised that it isn't possible to create indexes when using dynamic mode. This will be added to the schema of a collection as well as creation options.

**Comment by TomGrozev** [comment]
@rxndxm This has been implemented. Please check out the development branch to use the feature. You may have to view the docs locally or check the code on how to supply options.
