### ISSUE TITLE
Add support for COLLECT high-level query operation

### ISSUE THREAD

**Issue by hengestone** [TomGrozev/arangox_ecto#45]
### ArangoXEcto version

v1.0.0

### Feature type

New functionality

### Proposed functionality

Support building queries with `Ecto.Query` for COLLECT, AGGREGATE INTO operations
https://www.arangodb.com/docs/stable/aql/operations-collect.html

### Use case

Allowing Ecto Queries like
```
from(dc in DataCollection,
     collect: [city: dc.city, interval_start: dc.interval_start_ms],
     into: [dc_collect: :dc]
     select: [
       city: :city,
       interval_start: :interval_start,
       dc: :dc_collect
     ]
```

Needs variants for `collect_aggregate` and `collect_with_count_into` as well as `with_count_into` and `keep`.

### Version changes

None

### External dependencies

None

### Additional Context

Might need support for `fragments` to be really useful.

**Comment by TomGrozev** [comment]
As @mpoeter said, these arguments are stored in the `Ecto.Query` module and hence cannot be directly implemented. 

You can however query directly with the AQL using the `ArangoCEcto.aql_query/4` function. Checkout this https://hexdocs.pm/arangox_ecto/ArangoXEcto.html#aql_query/4 and https://hexdocs.pm/arangox_ecto/ArangoXEcto.html#raw_to_struct/2.

**Comment by hengestone** [comment]
Thanks - yes, I'm using `aql_query` :+1:
