### ISSUE TITLE
Edges do not support keyOptions

### ISSUE THREAD

**Issue by benknowles** [TomGrozev/arangox_ecto#46]
### ArangoXEcto version

latest

### Feature type

Change to existing functionality

### Proposed functionality

I wanted to create an issue first before proposing a PR.

But, essentially for a custom edge module the following doesn't work, like it does on a normal schema:
```
  options [
    keyOptions: %{type: :uuid}
  ]
```
This is silently ignored and the edge collection will get created with an integer key.

I was thinking, is there any reason not to use Migrate.collection and pass in collection_opts like is done in the `behavior/schema.ex`?

The edge creation does essentially the same, except by [directly posting](https://github.com/benknowles/arangox_ecto/blob/e70c31f2fe42b78e284e9e1082fe4815f0151d1f/lib/arangox_ecto.ex#L764).

### Use case

Supporting UUID primary keys on edge collections

**Comment by TomGrozev** [comment]
Hi @benknowles, sorry it took so long to respond to this issue, I have been on an extended period of leave.

I believe this is just an oversight for the edges. Will add for next release.

**Comment by TomGrozev** [comment]
Changes are in the develop branch, pending publish to v1.1.1
