### ISSUE TITLE
unique_constraint not recognized

### ISSUE THREAD

**Issue by jamilabreu** [TomGrozev/arangox_ecto#49]
### ArangoXEcto version

0.5.4

### Elixir and OTP version

1.14.0

### Ecto version

3.8.4

### ArangoDB version

3.9.2

### Steps to Reproduce

Insert an object with this changeset:

> def changeset(params, attrs) do
>     params
>     |> cast(attrs, [:url])
>     |> validate_required([:url])
>     |> unique_constraint(:url, name: "url_contraint")
> end

  

### Expected Behavior

It should recognize the `unique_constraint` function and insert the error

### Observed Behavior

  This error is thrown: 
  

>  ** (Ecto.ConstraintError) constraint error when attempting to insert struct:
> 
>     * unique constraint violated - in index idx_1744439301884608512 of type hash over 'url'; conflicting key: 98dc9b27-3161-4c9a-a510-d179e6079202 (unique_constraint)
> 
> If you would like to stop this constraint violation from raising an
> exception and instead add it as an error to your changeset, please
> call `unique_constraint/3` on your changeset with the constraint
> `:name` as an option.

**Comment by TomGrozev** [comment]
The issue you are having is that the index that you created doesn't have a name associated so the name "idx_1744439301884608512" is automatically generated. You specify the name "url_constraint" on the unique_constraint/3 function. You have a name mismatch here, so just create the index with the same name (docs here: [Ecto docs](https://hexdocs.pm/ecto/Ecto.Changeset.html#unique_constraint/3)).

I see you are using quite an old version of ArangoXEcto, might I suggest upgrading (if you have a specific reason you haven't I would be curious to know why you can't). This constraint issue is also documented in a later version of ArangoXEcto.

**Comment by jamilabreu** [comment]
Sorry, that's my arangox version, for arangox_ecto i'm on 1.1.1 :)

I tried implementing that named index with:

>   indexes([
>     [fields: [:url], name: "links_url_index", unique: true]
>   ])

with this in my changeset:

> |> unique_constraint(:url, name: :links_url_index)

  
  and still get:

> ** (Ecto.ConstraintError) constraint error when attempting to insert struct:
> 
>     * unique constraint violated - in index links_url_index of type hash over 'url'; conflicting key: 3b07a1d2-7419-4aa2-abd3-9294da340fe9 (unique_constraint)
> 
> If you would like to stop this constraint violation from raising an
> exception and instead add it as an error to your changeset, please
> call `unique_constraint/3` on your changeset with the constraint
> `:name` as an option.
> 
> The changeset defined the following constraints:
> 
>     * links_url_index (unique_constraint)

**Comment by TomGrozev** [comment]
I have pushed a fix to this to the develop branch. Turns out Ecto now wants the constraint name returned instead of the error message. This will be published in the next minor version (will probably actually be 1.2.0 as that is almost staged for release).

**Comment by jamilabreu** [comment]
😍 thanks!!
