### ISSUE TITLE
 ArangoXEcto.aql_query insert

### ISSUE THREAD

**Issue by mrsisk** [TomGrozev/arangox_ecto#57]
### ArangoXEcto version

1.2.0

### Elixir and OTP version

1.13.4

### Ecto version

3.7.2

### ArangoDB version

3.10.2

### Steps to Reproduce

 `ArangoXEcto.aql_query(Repo, "insert {name: \"name\"} into users")`

### Expected Behavior

To insert the document into user collection

### Observed Behavior

`{:error,
 %Arangox.Error{
   endpoint: "http://localhost:8529",
   error_num: 1652,
   message: "AQL: unregistered collection used in transaction: users [write] (while parsing)",
   status: 400
 }`

### Additional Context

`ArangoXEcto.aql_query/4` only works when  reading from the database. however it fails when doing any write operations such as insert or update.

**Comment by TomGrozev** [comment]
You need to pass the `:write` argument to the `ArangoXEcto.aql_query/4` function for any write operations. I have added some documentation to the function to clarify it.
